#[[redirects]]
#from = "/home"
#to = "/index.html"
#status =200
[[redirects]]
from="/google"
to="https://www.google.com"
status=301

[[redirects]]
from='/flavortown'
to ='https://flavortown.herokuapp.com/'
status=200

[[redirects]]
from="/home"
to ="/index.html"
status=200