#[[redirects]]
#from = "/home"
#to = "/index.html"
#status =200
[[redirects]]
from="/google"
to="https://www.google.com"
status=404
force=true

[[redirects]]
from="/flavortown"
to ="https://flavortown.herokuapp.com/index.html"
status=200

[[redirects]]
from="/home"
to ="/index.html"
status=200